services:
  - type: web
    name: test
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: SAAS_BACKEND_URL
        value: https://bugsaas.onrender.com
      - key: SITE_TOKEN
        value: site-token-taskflow-demo
